// <auto-generated />
namespace KNSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _add_column_student_address : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_add_column_student_address));
        
        string IMigrationMetadata.Id
        {
            get { return "202109131450064__ add_column_student_address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
